#!/usr/bin/env python3
"""Load AVO eval JSON receipts into a standing knowledge card.

Does not import or edit ``research.tools.avo_loop``. Receipts are the oracle
stdout shape from ``python -m research.tools.avo_eval`` (status, score,
provenance). Durable law stays in ``research/notes/kb_avo_eval.md``.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Final

ROOT: Final[Path] = Path(__file__).resolve().parents[1]
RECEIPTS_DIR: Final[Path] = ROOT / "research" / "reports" / "avo_receipts"
CARD_PATH: Final[Path] = ROOT / "research" / "notes" / "kb_avo_receipts.md"
MAX_RECEIPTS: Final[int] = 12
MAX_DIAG_CHARS: Final[int] = 160
VALID_STATUSES: Final[frozenset[str]] = frozenset(
    {"PASS", "FAIL", "FAIL-CLOSED", "NOT_READY", "REGRESSION", "TIE"}
)


class AvoCardsError(ValueError):
    """Rejected receipt or card render."""


def _as_receipt(raw: Any, source: Path) -> dict[str, Any] | None:
    if not isinstance(raw, dict):
        return None
    status = raw.get("status")
    if status not in VALID_STATUSES:
        return None
    is_valid = raw.get("is_valid")
    if not isinstance(is_valid, bool) or (status == "PASS" and not is_valid):
        return None
    metrics = raw.get("metrics") if isinstance(raw.get("metrics"), dict) else {}
    provenance = (
        metrics.get("provenance") if isinstance(metrics.get("provenance"), dict) else {}
    )
    diags = raw.get("diagnostics") if isinstance(raw.get("diagnostics"), list) else []
    diag0 = ""
    if diags and isinstance(diags[0], str):
        diag0 = diags[0].strip()[:MAX_DIAG_CHARS]
    return {
        "source": source.name,
        "status": str(status),
        "is_valid": is_valid,
        "improved": raw.get("improved") is True,
        "score": raw.get("score"),
        "mode": str(raw.get("mode") or ""),
        "target": str(provenance.get("config") or metrics.get("target") or ""),
        "fingerprint": str(provenance.get("fingerprint") or ""),
        "compile_mode": str(provenance.get("compile_mode") or ""),
        "diagnostic": diag0,
    }


def load_receipts(receipts_dir: Path = RECEIPTS_DIR) -> list[dict[str, Any]]:
    if not receipts_dir.is_dir():
        return []
    rows: list[dict[str, Any]] = []
    for path in sorted(receipts_dir.glob("*.json")):
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise AvoCardsError(f"unreadable receipt {path}: {exc}") from exc
        receipt = _as_receipt(payload, path)
        if receipt is None:
            raise AvoCardsError(f"not an avo_eval receipt: {path.name}")
        rows.append(receipt)
    return rows[-MAX_RECEIPTS:]


def render_card(receipts: list[dict[str, Any]]) -> str:
    lines = [
        "---",
        "id: KB-AVO-RECEIPTS-01",
        "title: Latest AVO eval receipts",
        "tags: [knowledge-card, avo, receipts, oracle]",
        "created: 2026-08-23",
        "---",
        "",
        "# KB-AVO-RECEIPTS-01: Latest AVO receipts",
        "",
        "Generated by `python -m conductor.avo_cards load`. Oracle is",
        "`python -m research.tools.avo_eval` (do not dump traces here).",
        "",
    ]
    if not receipts:
        lines.append("No receipts in `research/reports/avo_receipts/`.")
        lines.append("")
        return "\n".join(lines)
    lines.append("| status | valid | improved | mode | score | target | fingerprint |")
    lines.append("|---|---|---|---|---|---|---|")
    for row in receipts:
        score = row["score"]
        score_s = "" if score is None else str(score)
        target = (row["target"] or "—").replace("|", "/")
        fp = (row["fingerprint"] or "—")[:12]
        lines.append(
            f"| {row['status']} | {row['is_valid']} | {row['improved']} | "
            f"{row['mode'] or '—'} | {score_s or '—'} | `{target}` | `{fp}` |"
        )
    fails = [r for r in receipts if r["status"] != "PASS" and r["diagnostic"]]
    if fails:
        lines.append("")
        lines.append("Last fail diagnostic (trimmed):")
        lines.append(f"- {fails[-1]['diagnostic']}")
    lines.append("")
    return "\n".join(lines)


def write_card(
    receipts: list[dict[str, Any]],
    *,
    path: Path = CARD_PATH,
) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_card(receipts), encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Load AVO eval receipts into a knowledge card"
    )
    parser.add_argument("command", choices=["load"])
    parser.add_argument("--receipts-dir", type=Path, default=RECEIPTS_DIR)
    parser.add_argument("--card", type=Path, default=CARD_PATH)
    args = parser.parse_args(argv)
    try:
        receipts = load_receipts(args.receipts_dir)
        path = write_card(receipts, path=args.card)
    except AvoCardsError as exc:
        print(json.dumps({"error": str(exc)}), file=sys.stderr)
        return 2
    print(json.dumps({"card": str(path), "receipts": len(receipts)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
