//! Differential parity test: `forge::bash_guard::check` and
//! `forge::write_targets::repo_write_targets` against a corpus of commands,
//! compared to `guard_parity_expected.json` -- frozen output captured from the
//! Python `_bash_guard.check` / `bash_write_targets.repo_write_targets` at fixture
//! authoring time (see `scripts/generate_guard_parity_fixture.py`... generated by
//! a one-off script, not checked in; regenerate by running `_bash_guard.check`
//! and `bash_write_targets.repo_write_targets` over `guard_parity_corpus.json`
//! with repo_root `/repo` if either module's behaviour changes on purpose).
//!
//! `src/tooling/hooks/claude/test_guard_parity_corpus.py` is the Python-side
//! twin: it loads the SAME two fixture files and asserts Python still produces
//! the frozen expected values. Together the two tests pin both implementations
//! to one shared ground truth instead of to each other directly.
//!
//! This binary crate has no lib target, so the modules under test are compiled
//! in via `#[path]` rather than an external `extern crate forge` import.

#[path = "../src/bash_guard.rs"]
mod bash_guard;
#[path = "../src/write_targets.rs"]
mod write_targets;

use std::path::Path;

use serde::Deserialize;

#[derive(Deserialize)]
struct ExpectedEntry {
    command: String,
    blocked: bool,
    reason: Option<String>,
    write_targets: Vec<String>,
}

fn load_expected() -> Vec<ExpectedEntry> {
    let raw = include_str!("fixtures/guard_parity_expected.json");
    serde_json::from_str(raw).expect("guard_parity_expected.json must be valid JSON")
}

#[test]
fn corpus_has_at_least_forty_new_commands_beyond_the_python_test_suite() {
    let expected = load_expected();
    // 36 commands come from `test_bash_guard.py`'s 9 existing tests (with
    // duplicates collapsed); the rest are new, hand-written for this PR.
    assert!(
        expected.len() >= 76,
        "expected >= 36 existing + 40 new = 76 corpus entries, got {}",
        expected.len()
    );
}

#[test]
fn bash_guard_matches_python_on_every_corpus_command() {
    let expected = load_expected();
    let mut failures = Vec::new();
    for entry in &expected {
        let reason = bash_guard::check(&entry.command);
        let blocked = reason.is_some();
        if blocked != entry.blocked || reason != entry.reason {
            failures.push(format!(
                "command={:?}\n  expected: blocked={} reason={:?}\n  actual:   blocked={} reason={:?}",
                entry.command, entry.blocked, entry.reason, blocked, reason
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} guard mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn write_targets_match_python_on_every_corpus_command() {
    let expected = load_expected();
    let repo_root = Path::new("/repo");
    let mut failures = Vec::new();
    for entry in &expected {
        let targets = write_targets::repo_write_targets(&entry.command, repo_root);
        if targets != entry.write_targets {
            failures.push(format!(
                "command={:?}\n  expected: {:?}\n  actual:   {:?}",
                entry.command, entry.write_targets, targets
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} write-target mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
